import Head from 'next/head'
import Link from 'next/link';
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import { useState } from 'react';

export default function Home() {

  const [products, setProducts] = useState([])

  const callAPI = async () => {
    try {
      const res = await fetch(`https://63799da27eb4705cf28236c1.mockapi.io/api/products`);
      const data = await res.json();
      setProducts(data)
    } catch (err) {
      console.log(err);
    }
  };

  callAPI()


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://app.snipcart.com" />
        <link rel="preconnect" href="https://cdn.snipcart.com" />
        <link rel="stylesheet" href="https://cdn.snipcart.com/themes/v3.2.2/default/snipcart.css" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a>Ecommerce!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          {products.map(product => {
            return (
              <div key={product.id} className={styles.card}>
                <Link href={`/products/${product.id}`}>
                  <Image className={styles.img} src={product.image} alt={`Preview of ${product.title}`} />
                  <h3>{product.title}</h3>
                  <p className={styles.cardDescription}>{product.description}</p>
                  <p>${product.price}</p>
                </Link>
                <p>
                  <button className="snipcart-add-item"
                    data-item-id={product.id}
                    data-item-image={product.image}
                    data-item-name={product.title}
                    data-item-price={product.price}
                  >
                    Add to Cart
                  </button>
                </p>
              </div>
            );
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
      <script async src="https://cdn.snipcart.com/themes/v3.2.2/default/snipcart.js" />
      <div hidden id="snipcart" data-api-key="NzMxYWUyMDItYzc5ZC00NDkzLWJhMDktYmMyMWE3MGMwNjk2NjM4MDQ1MTA5MDU5NTcyODg3" />
    </div>
  )
}
